# Generated by Django 5.2.11 on 2026-02-15 17:43

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='format: required, max-64', max_length=64, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('grid', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Worksheet',
                'verbose_name_plural': 'Worksheets',
                'db_table': 'worksheets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='format: required, max-64', max_length=64, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('worksheets', models.ManyToManyField(blank=True, help_text='format: not required', to='spreadsheet.worksheet', verbose_name='Worksheets')),
            ],
            options={
                'verbose_name': 'Workbook',
                'verbose_name_plural': 'Workbooks',
                'db_table': 'workbooks',
                'ordering': ['name'],
            },
        ),
    ]
