# Generated by Django 5.2.10 on 2026-02-03 10:46

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_name', models.CharField(help_text='format: required, max-64', max_length=64, verbose_name='Last name')),
                ('first_name', models.CharField(help_text='format: required, max-32', max_length=32, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='Middle name')),
                ('birth_date', models.DateField(blank=True, help_text='format: Y-m-d, not required', null=True, verbose_name='Birth date')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='last_name')),
                ('union_number', models.PositiveIntegerField(help_text='format: not required', null=True, unique=True, verbose_name='Union number')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('email', models.EmailField(blank=True, help_text='format: not required, max-254', max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='format: not required, max-15', max_length=15, null=True, verbose_name='Phone number')),
                ('address', models.CharField(blank=True, help_text='format: not required, max-128', max_length=128, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, help_text='format: not required, max-6', max_length=6, null=True, verbose_name='Zip code')),
                ('province', models.CharField(blank=True, help_text='format: not required, max-64', max_length=64, null=True, verbose_name='Province')),
                ('author', models.ForeignKey(default=1, help_text='format: not required, default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='archer_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Archer',
                'verbose_name_plural': 'Archers',
                'db_table': 'archers',
                'ordering': ['last_name'],
            },
        ),
    ]
