# Generated by Django 5.2.10 on 2026-02-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_media', '0001_initial'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archer',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_media.customimage', verbose_name='Image'),
        ),
    ]
