# Generated by Django 5.2.11 on 2026-03-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringwizard',
            name='sub_title',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='scoringwizard',
            name='title',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='Title'),
        ),
    ]
