# Generated by Django 5.2.11 on 2026-02-08 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_media', '0001_initial'),
        ('scoring', '0002_agegrouppage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegrouppage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custom_media.customimage', verbose_name='Agegroup Photo'),
        ),
    ]
