# Generated by Django 5.2.11 on 2026-03-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scoringwizard_sub_title_scoringwizard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringwizard',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Title'),
        ),
    ]
