# Generated by Django 5.2.11 on 2026-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_scoringwizard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringwizard',
            name='sub_title',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Sub Title'),
        ),
    ]
