# Generated by Django 5.2.11 on 2026-02-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_agegrouppage_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-start_date'], 'verbose_name': 'Round', 'verbose_name_plural': 'Rounds'},
        ),
    ]
