# Generated by Django 5.2.11 on 2026-03-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_scoringwizard_sub_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringwizard',
            options={'ordering': ['name'], 'verbose_name': 'Scoring Wizard', 'verbose_name_plural': 'Scoring Wizards'},
        ),
    ]
