# Generated by Django 5.2.11 on 2026-02-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_round_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['start_date'], 'verbose_name': 'Round', 'verbose_name_plural': 'Rounds'},
        ),
    ]
