# Generated by Django 5.2.11 on 2026-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_alter_scoringwizard_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringwizard',
            name='scoring_type',
            field=models.CharField(choices=[('I', 'Individual'), ('T', 'Team'), ('R', 'Round'), ('C', 'Competition')], default='I', max_length=3),
        ),
    ]
