# Generated by Django 5.2.11 on 2026-02-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_streamformpage_mysubmissionrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='agegroups',
            field=models.ManyToManyField(blank=True, help_text='format: not required', to='scoring.agegroup', verbose_name='Other allowed AgeGroups'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='from_year',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='From year'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='until_year',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='Until year'),
        ),
    ]
