# Generated by Django 5.2.11 on 2026-02-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_streamformpage_mysubmissionrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroup',
            name='agegroups',
            field=models.ManyToManyField(blank=True, help_text='format: not required', related_name='+', to='scoring.agegroup', verbose_name='Allowed AgeGroups'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='from_year',
            field=models.PositiveIntegerField(default=0, help_text='format: required', verbose_name='From year'),
        ),
        migrations.AddField(
            model_name='agegroup',
            name='until_year',
            field=models.PositiveIntegerField(default=0, help_text='format: required', verbose_name='Until year'),
        ),
    ]
