# Generated by Django 5.2.11 on 2026-03-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_agegroup_agegroups_agegroup_from_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='teammembership_team', to='scoring.team', verbose_name='Team'),
        ),
    ]
