# Generated by Django 5.2.11 on 2026-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_agegroup_agegroups_agegroup_from_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='agegroups',
            field=models.ManyToManyField(blank=True, help_text='format: not required', to='scoring.agegroup', verbose_name='Allowed AgeGroups'),
        ),
    ]
