# Generated by Django 5.2.11 on 2026-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_alter_agegroup_agegroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='from_year',
            field=models.PositiveIntegerField(blank=True, help_text='format: required', null=True, verbose_name='From year'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='until_year',
            field=models.PositiveIntegerField(blank=True, help_text='format: required', null=True, verbose_name='Until year'),
        ),
    ]
