# Generated by Django 5.2.11 on 2026-03-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_alter_teammembership_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinemembership',
            name='discipline',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='disciplinememberships', to='scoring.discipline', verbose_name='Discipline'),
        ),
    ]
