# Generated by Django 5.2.11 on 2026-02-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_alter_agegroup_from_year_alter_agegroup_until_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='agegroups',
            field=models.ManyToManyField(blank=True, help_text='format: not required', to='scoring.agegroup', verbose_name='Other allowed AgeGroups'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='from_year',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='From year'),
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='until_year',
            field=models.PositiveIntegerField(blank=True, help_text='format: not required', null=True, verbose_name='Until year'),
        ),
    ]
