# Generated by Django 5.2.11 on 2026-03-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_alter_disciplinemembership_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymembership',
            name='category',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='categorymembership_category_items', to='scoring.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scoring.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='competitionmembership',
            name='round',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='competitionmembership_round', to='scoring.round', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='roundmembership',
            name='round',
            field=models.ForeignKey(default=1, help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='roundmembership_round', to='scoring.round', verbose_name='Round'),
        ),
    ]
