# Generated by Django 5.2.11 on 2026-03-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_alter_categorymembership_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundmembership',
            name='archer',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='roundmembership_archer', to='scoring.archer', verbose_name='Archer'),
        ),
    ]
