# Generated by Django 5.2.11 on 2026-03-14 05:20

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_alter_roundmembership_archer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end_time',
            field=models.TimeField(blank=True, help_text='format: H:M, not required', null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_time',
            field=models.TimeField(blank=True, help_text='format: H:M, not required', null=True, verbose_name='Start time'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, help_text='format: not required', null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='Default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='solution_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'db_table': 'solutions',
                'ordering': ['name'],
            },
        ),
    ]
