# Generated by Django 5.2.11 on 2026-03-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_alter_round_end_time_alter_round_start_time_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmembership',
            name='competition',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.CASCADE, related_name='competitionmembership_competition', to='scoring.competition', verbose_name='Competition'),
        ),
    ]
