# Generated by Django 5.2.11 on 2026-03-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0015_alter_archer_union_number_collection_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(help_text='format: required', on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='scoring.club', verbose_name='Club'),
        ),
    ]
