# Generated by Django 5.2.11 on 2026-03-18 09:28

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0016_alter_clubmembership_club'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultWizard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('result_type', models.CharField(choices=[('I', 'Individual'), ('T', 'Team'), ('R', 'Round'), ('C', 'Competition')], default='I', max_length=1)),
                ('author', models.ForeignKey(default=1, help_text='Default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='resultwizard_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Result Wizard',
                'verbose_name_plural': 'Result Wizards',
                'db_table': 'resultwizards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('author', models.ForeignKey(default=1, help_text='Default=1 (superuser)', on_delete=django.db.models.deletion.PROTECT, related_name='scoringtype_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('scoringsheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoringtype_scoringsheet', to='scoring.scoringsheet', verbose_name='Scoring Sheet')),
            ],
            options={
                'verbose_name': 'Scoring Type',
                'verbose_name_plural': 'Scoring Types',
                'db_table': 'scoringtypes',
                'ordering': ['name'],
            },
        ),
    ]
