# Generated by Django 5.2.11 on 2026-03-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0017_resultwizard_scoringtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultwizard',
            name='scoringtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoringtype_scoringsheet', to='scoring.scoringtype', verbose_name='Scoring Type'),
        ),
    ]
